# Generated by Django 5.2 on 2025-11-03 12:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 11 digits.', regex='^\\d{11}$')], verbose_name='Phone Number')),
                ('address', models.CharField(max_length=700, verbose_name='Address')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='Any notes about your order?')),
                ('total_price', models.PositiveIntegerField(blank=True, verbose_name='Total Price')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is order paid?')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Not Paid'), (1, 'Processing'), (2, 'Posted'), (3, 'Delivered'), (4, 'Canceled'), (5, 'Returned')], default=0, verbose_name='Order Status')),
                ('zarinpal_authority', models.CharField(blank=True, max_length=255, verbose_name='Zarinpal Authority')),
                ('zarinpal_ref_id', models.CharField(blank=True, max_length=150, verbose_name='Zarinpal Reference ID')),
                ('zarinpal_data', models.TextField(blank=True, verbose_name='Zarinpal Data')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='Datetime Modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('price', models.PositiveIntegerField(blank=True, verbose_name='Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Order')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.productvariant', verbose_name='Product Variant')),
            ],
        ),
    ]
