# Generated by Django 5.2 on 2025-11-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='datetime_payment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment Datetime'),
        ),
    ]
