# Generated by Django 5.2 on 2025-11-09 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be exactly 11 digits starting with '09'.", regex='^09\\d{9}$')], verbose_name='Phone Number'),
        ),
    ]
