# Generated by Django 5.2 on 2025-10-27 13:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('short_description', models.CharField(max_length=700, verbose_name='Short Description')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is The Product Active ?')),
                ('category', models.CharField(choices=[('Shoes', [('w-summer', 'Women Summer Shoes'), ('w-casual', 'Women Casual Shoes'), ('w-sport', 'Women Sport Shoes'), ('w-medical', 'Women Medical Shoes'), ('w-formal', 'Women Formal Shoes'), ('w-majlesi', 'Women Majlesi Shoes'), ('w-winter', 'Women Winter Shoes'), ('m-summer', 'Men Summer Shoes'), ('m-casual', 'Men Casual Shoes'), ('m-sport', 'Men Sport Shoes'), ('m-medical', 'Men Medical Shoes'), ('m-formal', 'Men Formal Shoes'), ('m-majlesi', 'Men Majlesi Shoes'), ('m-winter', 'Men Winter Shoes')]), ('Purse', [('women_purse', 'Women Purse'), ('men_purse', 'Men Purse'), ('bags', 'Bags')]), ('Wearing', [('coat', 'Coat'), ('hat', 'Hat')]), ('Accessory', [('women_belt', 'Women Belt'), ('men_belt', 'Men Belt'), ('kids_belt', 'Kids Belt'), ('wallet', 'Wallet'), ('keyhan', 'Keyhan'), ('hand_bag', 'Hand Bag'), ('card', 'Card Holder'), ('buttom', 'Buttom')]), ('Tools', [('polish', 'Polish')])], max_length=50, verbose_name='Category')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='Datetime Modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='products/covers/', verbose_name='Product Cover')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='products.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('recommend', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Do you recommend this product to others?')),
                ('rate', models.PositiveIntegerField(blank=True, choices=[(1, '1/5  Very Bad'), (2, '2/5  Low Quality'), (3, '3/5  Average'), (4, '4/5  Good'), (5, '5/5  Perfect')], null=True, verbose_name='Rate this product from 1-5')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is this comment active')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='Datetime Modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('we', 'White'), ('bk', 'Black'), ('yw', 'Yellow'), ('re', 'Red'), ('be', 'Blue'), ('he', 'HoneyLike'), ('bn', 'Brown'), ('wn', 'Wheaten'), ('cm', 'Cream')], max_length=2, null=True, verbose_name='Color')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is the variant active?')),
                ('size', models.PositiveIntegerField(blank=True, choices=[(85, '85 cm'), (95, '95 cm'), (105, '105 cm'), (115, '115 cm'), (125, '125 cm'), (135, '135 cm')], null=True, verbose_name='Size')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurseVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('we', 'White'), ('bk', 'Black'), ('yw', 'Yellow'), ('re', 'Red'), ('be', 'Blue'), ('he', 'HoneyLike'), ('bn', 'Brown'), ('wn', 'Wheaten'), ('cm', 'Cream')], max_length=2, null=True, verbose_name='Color')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is the variant active?')),
                ('size', models.PositiveIntegerField(blank=True, choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large')], null=True, verbose_name='Size')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShoesVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('we', 'White'), ('bk', 'Black'), ('yw', 'Yellow'), ('re', 'Red'), ('be', 'Blue'), ('he', 'HoneyLike'), ('bn', 'Brown'), ('wn', 'Wheaten'), ('cm', 'Cream')], max_length=2, null=True, verbose_name='Color')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is the variant active?')),
                ('size', models.PositiveIntegerField(blank=True, choices=[(36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47)], null=True, verbose_name='Size')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoes_stock', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('we', 'White'), ('bk', 'Black'), ('yw', 'Yellow'), ('re', 'Red'), ('be', 'Blue'), ('he', 'HoneyLike'), ('bn', 'Brown'), ('wn', 'Wheaten'), ('cm', 'Cream')], max_length=2, null=True, verbose_name='Color')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is the variant active?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WearingVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('we', 'White'), ('bk', 'Black'), ('yw', 'Yellow'), ('re', 'Red'), ('be', 'Blue'), ('he', 'HoneyLike'), ('bn', 'Brown'), ('wn', 'Wheaten'), ('cm', 'Cream')], max_length=2, null=True, verbose_name='Color')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is the variant active?')),
                ('size', models.PositiveIntegerField(blank=True, choices=[(36, 36), (38, 38), (40, 40), (42, 42), (44, 44), (46, 46), (48, 48), (50, 50), (52, 52), (54, 54), (56, 56), (58, 58), (60, 60), (62, 62)], null=True, verbose_name='Size')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
