# Generated by Django 5.2 on 2025-11-03 12:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('short_description', models.CharField(max_length=700, verbose_name='Short Description')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is The Product Active ?')),
                ('sell_count', models.PositiveIntegerField(default=0, verbose_name='How many items of this product were sold?')),
                ('category', models.CharField(choices=[('Women', [('w-summer', 'Women Summer Shoes'), ('w-casual', 'Women Casual Shoes'), ('w-sport', 'Women Sport Shoes'), ('w-medical', 'Women Medical Shoes'), ('w-formal', 'Women Formal Shoes'), ('w-heels', 'Women Heels Shoes'), ('w-winter', 'Women Winter Shoes')]), ('Men', [('m-summer', 'Men Summer Shoes'), ('m-sport', 'Men Sport Shoes'), ('m-medical', 'Men Medical Shoes'), ('m-formal', 'Men Formal Shoes'), ('m-occasional', 'Men Occasional Shoes'), ('m-winter', 'Men Winter Shoes')]), ('Bags', [('Handbag', 'Handbag'), ('Shoulder bags', 'Shoulder bags'), ('office bag', 'office bag'), ('travel bag', 'travel bag'), ('backpack', 'backpack'), ('card holder', 'card holder'), ('coat bag', 'coat bag'), ('Checkbook bag', 'Checkbook bag')]), ('Clothing', [('m-jackets', 'Men Jackets'), ('w-jackets', 'Women Jackets'), ('hats', 'Hats')]), ('Accessory', [('m-accessories', 'Men'), ('w-accessories', 'Women')]), ('ShoesCare', [('medical-insole', 'Medical Insole'), ('wax', 'Wax')])], max_length=50, verbose_name='Category')),
                ('major_category', models.CharField(blank=True, choices=[('Women', 'Women'), ('Men', 'Men'), ('Bags', 'Bags'), ('Clothing', 'Clothing'), ('Accessory', 'Accessory'), ('ShoesCare', 'ShoesCare')], max_length=20, verbose_name='Major Category')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='Datetime Modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='products/covers/', verbose_name='Product Cover')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='products.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('text', models.TextField(verbose_name='Text')),
                ('recommend', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Do you recommend this product to others?')),
                ('rate', models.PositiveIntegerField(blank=True, choices=[(1, '1/5  Very Bad'), (2, '2/5  Low Quality'), (3, '3/5  Average'), (4, '4/5  Good'), (5, '5/5  Perfect')], null=True, verbose_name='Rate this product from 1-5')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is this comment active')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='Datetime Modified')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('we', 'White'), ('bk', 'Black'), ('yw', 'Yellow'), ('rd', 'Red'), ('be', 'Blue'), ('ce', 'Chocolate'), ('bn', 'Brown'), ('wn', 'Wheat'), ('lw', 'Lightyellow')], max_length=2, verbose_name='Color')),
                ('size', models.PositiveIntegerField(blank=True, choices=[('Women', [(36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42')]), ('Men', [(40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47')]), ('Bags', [(1, 'Small'), (2, 'Medium'), (3, 'Large')]), ('Clothing', [(36, '36'), (38, '38'), (40, '40'), (42, '42'), (44, '44'), (46, '46'), (48, '48'), (50, '50'), (52, '52'), (54, '54'), (56, '56'), (58, '58'), (60, '60'), (62, '62')]), ('Accessory', [(85, '85cm'), (95, '95cm'), (105, '105cm'), (115, '115cm'), (125, '125cm'), (135, '135cm')]), ('ShoesCare', [(36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45')])], null=True, verbose_name='Size')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is the variant active?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='Product')),
            ],
            options={
                'unique_together': {('product', 'color', 'size')},
            },
        ),
    ]
