# Generated by Django 5.2 on 2025-10-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Shoes', [('w-summer', 'Women Summer Shoes'), ('w-casual', 'Women Casual Shoes'), ('w-sport', 'Women Sport Shoes'), ('w-medical', 'Women Medical Shoes'), ('w-formal', 'Women Formal Shoes'), ('w-majlesi', 'Women Majlesi Shoes'), ('w-winter', 'Women Winter Shoes'), ('m-summer', 'Men Summer Shoes'), ('m-casual', 'Men Casual Shoes'), ('m-sport', 'Men Sport Shoes'), ('m-medical', 'Men Medical Shoes'), ('m-formal', 'Men Formal Shoes'), ('m-majlesi', 'Men Majlesi Shoes'), ('m-winter', 'Men Winter Shoes')]), ('Purse', [('women_purse', 'Women Purse'), ('men_purse', 'Men Purse'), ('bags', 'Bags')]), ('Wearing', [('coat', 'Coat'), ('hat', 'Hat')]), ('Accessory', [('women_belt', 'Women Belt'), ('men_belt', 'Men Belt'), ('kids_belt', 'Kids Belt'), ('wallet', 'Wallet'), ('keyhan', 'Keyhan'), ('hand_bag', 'Hand Bag'), ('card', 'Card Holder'), ('buttom', 'Buttom')]), ('Tool', [('polish', 'Polish')])], max_length=50, verbose_name='Category'),
        ),
    ]
