# Generated by Django 5.2 on 2025-11-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.BooleanField(default=False, verbose_name='Does this product have an offer?'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Offer Price'),
        ),
    ]
