# Generated by Django 5.2 on 2025-10-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorvariant',
            name='size',
            field=models.PositiveIntegerField(choices=[('Women', [(36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42)]), ('Men', [(40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47)]), ('Bags', [(1, 'Small'), (2, 'Medium'), (3, 'Large')]), ('Clothing', [(36, 36), (38, 38), (40, 40), (42, 42), (44, 44), (46, 46), (48, 48), (50, 50), (52, 52), (54, 54), (56, 56), (58, 58), (60, 60), (62, 62)]), ('Accessory', [(85, '85 cm'), (95, '95 cm'), (105, '105 cm'), (115, '115 cm'), (125, '125 cm'), (135, '135 cm')]), ('ShoesCare', [(36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45)])], max_length=20, verbose_name='Size'),
        ),
    ]
