# Generated by Django 5.2 on 2025-10-27 13:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wearingvariant',
            name='product',
        ),
        migrations.AlterField(
            model_name='accessoryvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories_variants', to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Shoes', [('w-summer', 'Women Summer Shoes'), ('w-casual', 'Women Casual Shoes'), ('w-sport', 'Women Sport Shoes'), ('w-medical', 'Women Medical Shoes'), ('w-formal', 'Women Formal Shoes'), ('w-majlesi', 'Women Majlesi Shoes'), ('w-winter', 'Women Winter Shoes'), ('m-summer', 'Men Summer Shoes'), ('m-casual', 'Men Casual Shoes'), ('m-sport', 'Men Sport Shoes'), ('m-medical', 'Men Medical Shoes'), ('m-formal', 'Men Formal Shoes'), ('m-majlesi', 'Men Majlesi Shoes'), ('m-winter', 'Men Winter Shoes')]), ('Bags', [('women_purse', 'Women Purse'), ('men_purse', 'Men Purse'), ('bags', 'Bags')]), ('Clothes', [('coat', 'Coat'), ('hat', 'Hat')]), ('Accessories', [('women_belt', 'Women Belt'), ('men_belt', 'Men Belt'), ('kids_belt', 'Kids Belt'), ('wallet', 'Wallet'), ('keyhan', 'Keyhan'), ('hand_bag', 'Hand Bag'), ('card', 'Card Holder'), ('buttom', 'Buttom')]), ('Tools', [('polish', 'Polish')])], max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='shoesvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoes_variants', to='products.product'),
        ),
        migrations.AlterField(
            model_name='toolvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools_variants', to='products.product'),
        ),
        migrations.CreateModel(
            name='BagVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('we', 'White'), ('bk', 'Black'), ('yw', 'Yellow'), ('re', 'Red'), ('be', 'Blue'), ('he', 'HoneyLike'), ('bn', 'Brown'), ('wn', 'Wheaten'), ('cm', 'Cream')], max_length=2, null=True, verbose_name='Color')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is the variant active?')),
                ('size', models.PositiveIntegerField(blank=True, choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large')], null=True, verbose_name='Size')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bags_variants', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClotheVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('we', 'White'), ('bk', 'Black'), ('yw', 'Yellow'), ('re', 'Red'), ('be', 'Blue'), ('he', 'HoneyLike'), ('bn', 'Brown'), ('wn', 'Wheaten'), ('cm', 'Cream')], max_length=2, null=True, verbose_name='Color')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is the variant active?')),
                ('size', models.PositiveIntegerField(blank=True, choices=[(36, 36), (38, 38), (40, 40), (42, 42), (44, 44), (46, 46), (48, 48), (50, 50), (52, 52), (54, 54), (56, 56), (58, 58), (60, 60), (62, 62)], null=True, verbose_name='Size')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_variants', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='PurseVariant',
        ),
        migrations.DeleteModel(
            name='WearingVariant',
        ),
    ]
