# Generated by Django 5.2 on 2025-11-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_offer_product_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Women', [('w-summer', 'Women Summer Shoes'), ('w-casual', 'Women Casual Shoes'), ('w-sport', 'Women Sport Shoes'), ('w-medical', 'Women Medical Shoes'), ('w-formal', 'Women Formal Shoes'), ('w-heels', 'Women Heels Shoes'), ('w-winter', 'Women Winter Shoes')]), ('Men', [('m-summer', 'Men Summer Shoes'), ('m-sport', 'Men Sport Shoes'), ('m-medical', 'Men Medical Shoes'), ('m-formal', 'Men Formal Shoes'), ('m-occasional', 'Men Occasional Shoes'), ('m-winter', 'Men Winter Shoes')]), ('Bags', [('hand-bag', 'Handbag'), ('shoulder-bags', 'Shoulder bags'), ('office-bag', 'Office bag'), ('travel-bag', 'Travel bag'), ('back-pack', 'Backpack'), ('card-holder', 'Card holder'), ('coat-bag', 'Coat bag'), ('checkbook-bag', 'Checkbook bag')]), ('Clothing', [('m-jackets', 'Men Jackets'), ('w-jackets', 'Women Jackets'), ('hats', 'Hats')]), ('Accessory', [('m-accessories', 'Men'), ('w-accessories', 'Women')]), ('ShoesCare', [('medical-insole', 'Medical insole'), ('wax', 'Wax')])], max_length=50, verbose_name='Category'),
        ),
    ]
