# Generated by Django 5.2 on 2025-10-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_wearingvariant_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoryvariant',
            name='color',
            field=models.CharField(blank=True, choices=[('we', 'White'), ('bk', 'Black'), ('yw', 'Yellow'), ('re', 'Red'), ('be', 'Blue'), ('ce', 'Chocolate'), ('bn', 'Brown'), ('wn', 'Wheat'), ('lw', 'Lightyellow')], max_length=2, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='bagvariant',
            name='color',
            field=models.CharField(blank=True, choices=[('we', 'White'), ('bk', 'Black'), ('yw', 'Yellow'), ('re', 'Red'), ('be', 'Blue'), ('ce', 'Chocolate'), ('bn', 'Brown'), ('wn', 'Wheat'), ('lw', 'Lightyellow')], max_length=2, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='clothevariant',
            name='color',
            field=models.CharField(blank=True, choices=[('we', 'White'), ('bk', 'Black'), ('yw', 'Yellow'), ('re', 'Red'), ('be', 'Blue'), ('ce', 'Chocolate'), ('bn', 'Brown'), ('wn', 'Wheat'), ('lw', 'Lightyellow')], max_length=2, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='shoesvariant',
            name='color',
            field=models.CharField(blank=True, choices=[('we', 'White'), ('bk', 'Black'), ('yw', 'Yellow'), ('re', 'Red'), ('be', 'Blue'), ('ce', 'Chocolate'), ('bn', 'Brown'), ('wn', 'Wheat'), ('lw', 'Lightyellow')], max_length=2, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='toolvariant',
            name='color',
            field=models.CharField(blank=True, choices=[('we', 'White'), ('bk', 'Black'), ('yw', 'Yellow'), ('re', 'Red'), ('be', 'Blue'), ('ce', 'Chocolate'), ('bn', 'Brown'), ('wn', 'Wheat'), ('lw', 'Lightyellow')], max_length=2, null=True, verbose_name='Color'),
        ),
    ]
