# Generated by Django 5.2 on 2025-11-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=400, verbose_name='Materials'),
        ),
    ]
