# Generated by Django 5.2 on 2025-11-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(choices=[('we', 'White'), ('bk', 'Black'), ('yw', 'Yellow'), ('rd', 'Red'), ('be', 'Blue'), ('ce', 'Chocolate'), ('bn', 'Brown'), ('wn', 'Wheat'), ('lw', 'Lightyellow')], max_length=2, verbose_name='Color'),
        ),
    ]
