# Generated by Django 5.2 on 2025-10-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_accessoryvariant_color_alter_bagvariant_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='major_category',
            field=models.CharField(default=1, max_length=10, verbose_name='Major Category'),
            preserve_default=False,
        ),
    ]
