# Generated by Django 5.2 on 2025-10-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_major_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='major_category',
            field=models.CharField(blank=True, max_length=10, verbose_name='Major Category'),
        ),
    ]
