# Generated by Django 5.2 on 2025-10-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_major_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='major_category',
            field=models.CharField(blank=True, choices=[('Shoes', 'Shoes'), ('Bags', 'Bags'), ('Clothes', 'Clothes'), ('Accessories', 'Accessories'), ('Tools', 'Tools')], max_length=20, verbose_name='Major Category'),
        ),
    ]
