# Generated by Django 5.2 on 2025-10-28 18:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_major_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoesvariant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='toolvariant',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='sell_count',
            field=models.PositiveIntegerField(default=0, verbose_name='How many items of this product were sold?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessoryvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_variants', to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Women', [('w-summer', 'Women Summer Shoes'), ('w-casual', 'Women Casual Shoes'), ('w-sport', 'Women Sport Shoes'), ('w-medical', 'Women Medical Shoes'), ('w-formal', 'Women Formal Shoes'), ('w-heels', 'Women Heels Shoes'), ('w-winter', 'Women Winter Shoes')]), ('Men', [('m-summer', 'Men Summer Shoes'), ('m-sport', 'Men Sport Shoes'), ('m-medical', 'Men Medical Shoes'), ('m-formal', 'Men Formal Shoes'), ('m-occasional', 'Men Occasional Shoes'), ('m-winter', 'Men Winter Shoes')]), ('Bags', [('Handbag', 'Handbag'), ('Shoulder bags', 'Shoulder bags'), ('office bag', 'office bag'), ('travel bag', 'travel bag'), ('backpack', 'backpack'), ('card holder', 'card holder'), ('coat bag', 'coat bag'), ('Checkbook bag', 'Checkbook bag')]), ('Clothing', [('m-jackets', 'Men Jackets'), ('w-jackets', 'Women Jackets'), ('hats', 'Hats')]), ('Accessory', [('m-accessories', 'Men'), ('w-accessories', 'Women')]), ('ShoesCare', [('medical-insole', 'Medical Insole'), ('wax', 'Wax')])], max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='major_category',
            field=models.CharField(blank=True, choices=[('Women', 'Women'), ('Men', 'Men'), ('Bags', 'Bags'), ('Clothing', 'Clothing'), ('Accessory', 'Accessory'), ('ShoesCare', 'ShoesCare')], max_length=20, verbose_name='Major Category'),
        ),
        migrations.CreateModel(
            name='ClothingVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('we', 'White'), ('bk', 'Black'), ('yw', 'Yellow'), ('re', 'Red'), ('be', 'Blue'), ('ce', 'Chocolate'), ('bn', 'Brown'), ('wn', 'Wheat'), ('lw', 'Lightyellow')], max_length=2, null=True, verbose_name='Color')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is the variant active?')),
                ('size', models.PositiveIntegerField(blank=True, choices=[(36, 36), (38, 38), (40, 40), (42, 42), (44, 44), (46, 46), (48, 48), (50, 50), (52, 52), (54, 54), (56, 56), (58, 58), (60, 60), (62, 62)], null=True, verbose_name='Size')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_variants', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('we', 'White'), ('bk', 'Black'), ('yw', 'Yellow'), ('re', 'Red'), ('be', 'Blue'), ('ce', 'Chocolate'), ('bn', 'Brown'), ('wn', 'Wheat'), ('lw', 'Lightyellow')], max_length=2, null=True, verbose_name='Color')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is the variant active?')),
                ('size', models.PositiveIntegerField(blank=True, choices=[(40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47)], null=True, verbose_name='Size')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='men_variants', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShoesCareVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('we', 'White'), ('bk', 'Black'), ('yw', 'Yellow'), ('re', 'Red'), ('be', 'Blue'), ('ce', 'Chocolate'), ('bn', 'Brown'), ('wn', 'Wheat'), ('lw', 'Lightyellow')], max_length=2, null=True, verbose_name='Color')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is the variant active?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoescare_variants', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WomenVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('we', 'White'), ('bk', 'Black'), ('yw', 'Yellow'), ('re', 'Red'), ('be', 'Blue'), ('ce', 'Chocolate'), ('bn', 'Brown'), ('wn', 'Wheat'), ('lw', 'Lightyellow')], max_length=2, null=True, verbose_name='Color')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is the variant active?')),
                ('size', models.PositiveIntegerField(blank=True, choices=[(36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42)], null=True, verbose_name='Size')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='women_variants', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ClotheVariant',
        ),
        migrations.DeleteModel(
            name='ShoesVariant',
        ),
        migrations.DeleteModel(
            name='ToolVariant',
        ),
    ]
